### ISSUE TITLE
Issue in training the dataset for custom shirt

### ISSUE THREAD

**Issue by Sumran99** [trinanjan12/pix2surf#1]
Hello, I am running the commands that you have provided and I have installed all the requirements. Due to compatibility issues, I have installed the cp version of the torch in the virtual environment of python 2.7. Now after running the command python train_map.py, there is an error of 

`The number of parameters: 7838850
Traceback (most recent call last):
  File "train_map.py", line 234, in <module>
    solver = MapNet()
  File "train_map.py", line 76, in __init__
    self.train_dataloader = DataLoader(self.train_dataset, batch_size=1, num_workers=self.args.num_workers, shuffle=True)
  File "/home/hani/.virtualenv/pymesh2.7/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/hani/.virtualenv/pymesh2.7/lib/python2.7/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
`
I had not changed any directory or image. 
![issue_github](https://user-images.githubusercontent.com/89527783/147845448-d3ec4600-5f10-4fd6-ad72-791effe29b66.png)

**Comment by Sumran99** [comment]
The error is due to different paths in run.py, train_seg.py, and train_map.py. The run.py has the default path of the pant front while train_seg.py and train_map.py have the default path of the shirt front. Due to this, the above error exits. After changing the path in these files you can get the final results.
